# Generated by Django 4.2.20 on 2025-03-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.CharField(blank=True, choices=[('surgeon', 'Surgeon'), ('gynecologist', 'Gynecologist'), ('psychiatrist', 'Psychiatrist'), ('urologist', 'Urologist'), ('paediatrician', 'Paediatrician'), ('opd', 'OPD')], max_length=50, null=True),
        ),
    ]
