from django.urls import path,include
from clinic import views

urlpatterns = [
    path("", views.hospital_dashboard, name="hospital_dashboard"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("accounts/", include("django.contrib.auth.urls")),
    # path("hospital_admin/", views.hospital_admin, name="hospital_admin"),
    # path("medical_dashboard/", views.medical_dashboard, name="medical_dashboard"),
    # path("medical_staff/", views.medical_staff, name="medical_staff"),
    # path("patients_list/", views.patients_list, name="patients_list"),
    # path("add_patients/", views.add_patients, name="add_patients"),
    # path("patient_dashboard/", views.patient_dashboard, name="patient_dashboard"),
    # path("pharmacy/", views.pharmacy, name="pharmacy"),
    # path("pharmacy_admin/", views.pharmacy_admin, name="pharmacy_admin"),
    # path("pharmacy_dashboard/", views.pharmacy_dashboard, name="pharmacy_dashboard"),
    # path("pharmacy_staff/", views.pharmacy_staff, name="pharmacy_staff"),
    # path("reception/", views.reception, name="reception"),
    # path("receptionist/", views.receptionist, name="receptionist"),
    # path("receptionist_dashboard/", views.receptionist_dashboard, name="receptionist_dashboard"),
    # path("receptionist_staff/", views.receptionist_staff, name="receptionist_staff"),
    # path("staff/", views.staff, name="staff"),
    # path("staff_dashboard/", views.staff_dashboard, name="staff_dashboard"),
    # path("staff_staff/", views.staff_staff, name="staff_staff"),
    # path("ward/", views.ward, name="ward"),
    # path("ward_admin/", views.ward_admin, name="ward_admin"),
    # path("ward_dashboard/", views.ward_dashboard, name="ward_dashboard"),
    # path("ward_staff/", views.ward_staff, name="ward_staff"),
    # path("ward_nurse/", views.ward_nurse, name="ward_nurse"),
    # path("ward_nurse_dashboard/", views.ward_nurse_dashboard, name="ward_nurse_dashboard"),
    # path("ward_nurse_staff/", views.ward_nurse_staff, name="ward_nurse_staff"),
    # path("ward_doctor/", views.ward_doctor, name="ward_doctor"),
    # path("ward_doctor_dashboard/", views.ward_doctor_dashboard, name="ward_doctor_dashboard"),
    # path("ward_doctor_staff/", views.ward_doctor_staff, name="ward_doctor_staff"),
    # path("ward_doctor_patient/", views.ward_doctor_patient, name="ward_doctor_patient"),
    # path("ward_doctor_patient_dashboard/", views.ward_doctor_patient_dashboard, name="ward_doctor_patient_dashboard"),
    # path("ward_doctor_patient_staff/", views.ward_doctor_patient_staff, name="ward_doctor_patient_staff"),
    # path("ward_doctor_patient_assessment/", views.ward_doctor_patient_assessment, name="ward_doctor_patient_assessment"),
    # path("ward_doctor_patient_assessment_dashboard/", views.ward_doctor_patient_assessment_dashboard, name="ward_doctor_patient_assessment_dashboard"),
    # path("ward_doctor_patient_assessment_staff/", views.ward_doctor_patient_assessment_staff, name="ward_doctor_patient_assessment_staff"),
    # path("ward_doctor_patient_assessment_prescription/", views.ward_doctor_patient_assessment_prescription, name="ward_doctor_patient_assessment_prescription"),
    # path("ward_doctor_patient_assessment_prescription_dashboard/", views.ward_doctor_patient_assessment_prescription_dashboard, name="ward_doctor_patient_assessment_prescription_dashboard"),
    # path("ward_doctor_patient_assessment_prescription_staff/", views.ward_doctor_patient_assessment_prescription_staff, name="ward_doctor_patient_assessment_prescription_staff"),
    # path("ward_doctor_patient_assessment_prescription_diagnosis/", views.ward_doctor_patient_assessment_prescription_diagnosis, name="ward_doctor_patient_assessment_prescription_diagnosis"),
    # path("ward_doctor_patient_assessment_prescription_diagnosis_dashboard/", views.ward_doctor_patient_assessment_prescription_diagnosis_dashboard, name="ward_doctor_patient_assessment_prescription_diagnosis_dashboard"),

]
